spring.application.name=zoo-jpa

spring.datasource.url= jdbc:mysql://localhost:3306/bootcamp16
spring.datasource.username=root
spring.datasource.password=!tn3tw0rk2020
spring.jpa.hibernate.ddl-auto=create-drop