spring.application.name=affable-bean-gateway

server.port=8080

#affable-bean-backend
spring.cloud.gateway.server.webmvc.routes[0].id=affable-bean-backend
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AFFABLE-BEAN-BACKEND
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/backend/**

#affable-bean-ui
spring.cloud.gateway.server.webmvc.routes[1].id=affable-bean-ui
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AFFABLE-BEAN-UI
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/affable-bean/ui/**, /css/**, /images/**

eureka.client.service-url.defaultZone=http://localhost:8083/eureka