spring.application.name=19-employee-inheritance


spring.datasource.url=jdbc:mysql://localhost:3306/bootcamp16
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop