spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.server.webmvc.routes[0].id=stateless-demo
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://STATELESSNESS-DEMO
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/counter/**

eureka.client.service-url.defaultZone=http://localhost:8083/eureka


